twig:
    file_name_pattern: '*.twig'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        breadcrumb_service: '@App\Services\BreadcrumbService'

when@test:
    twig:
        strict_variables: true
